;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="AbilityAttack.exist",DevComment="")
+GameplayTagList=(Tag="AbilityAttack.Slash1",DevComment="")
+GameplayTagList=(Tag="AbilityAttack.Slash2",DevComment="")
+GameplayTagList=(Tag="AbilityAttack.Slash3",DevComment="")
+GameplayTagList=(Tag="AttackFreeze",DevComment="")
+GameplayTagList=(Tag="Combo.Attack",DevComment="")
+GameplayTagList=(Tag="Combo.Continue",DevComment="")
+GameplayTagList=(Tag="Combo.Continue2",DevComment="")
+GameplayTagList=(Tag="Combo.Continue3",DevComment="")
+GameplayTagList=(Tag="Dodge",DevComment="")
+GameplayTagList=(Tag="DodgeAbility.NotPlayMontage",DevComment="")
+GameplayTagList=(Tag="Event.Combat.ComboWindow",DevComment="")
+GameplayTagList=(Tag="IaiCombo.ComboEnd",DevComment="")
+GameplayTagList=(Tag="IaiCombo.NextSlash1",DevComment="")
+GameplayTagList=(Tag="IaiCombo.NextSlash2",DevComment="")
+GameplayTagList=(Tag="Iaido.End",DevComment="")
+GameplayTagList=(Tag="StanceAbility.Freeze",DevComment="")
+GameplayTagList=(Tag="StanceAbility.Normal",DevComment="")
+GameplayTagList=(Tag="StanceFreeze",DevComment="")

